version: '3'

#docker-compose -f docker/docker-compose.yml up
services:
  database_gdo:
    build:
      dockerfile: docker/DockerfileDatabase
      context: ../
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Cerrito844
  phpmyadmin_gdo:
    image: phpmyadmin/phpmyadmin
    links:
      - database_gdo
    environment:
      PMA_HOST: database_gdo
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: "Cerrito844"
    ports:
      - "4001:80"
  server_gdo:
    depends_on:
      - database_gdo
    links:
      - database_gdo:database_gdo
    build:
      dockerfile: docker/DockerfileServer
      context: ../
    volumes:
      - "../:/gdo"
    ports:
      - "4000:3000"
      - "9229:9229"
      - "5858:5858"
    restart: always